import path from "node:path";
import type { RenderOptions, RenderResult, TimelineItem, Transcript } from "./types.js";
import { redactObjectStrings } from "./redaction.js";

const DEFAULT_MAX_INLINE_CHARS = 3_500;

type DisplayItem =
  | { kind: "timeline"; item: TimelineItem }
  | { kind: "tool-pair"; call: TimelineItem; result?: TimelineItem };

export function renderTranscript(input: Transcript, options: RenderOptions = {}): RenderResult {
  const redaction = options.redact === false ? { value: input, count: 0 } : redactObjectStrings(input);
  const transcript = redaction.value;
  const title = options.title ?? transcript.title ?? "Codex session";
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const maxInlineChars = options.maxInlineChars ?? DEFAULT_MAX_INLINE_CHARS;
  const displayItems = buildDisplayItems(transcript.items);
  const sourcePath = options.sourcePath ?? transcript.sourcePath;
  const project = deriveProject(transcript, sourcePath);
  const agent = deriveAgent(transcript, sourcePath);
  const model = stringMeta(transcript.metadata.model) ?? stringMeta(transcript.metadata.currentModel) ?? "unknown model";
  const duration = formatDuration(transcript.startedAt, transcript.endedAt);

  const body = displayItems.map((item) => renderDisplayItem(item, maxInlineChars)).join("\n");
  const stats = { ...transcript.stats, redactionCount: redaction.count };

  const html = `<!doctype html>
<html lang="zh-CN" data-theme="auto">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} · what7</title>
  <style>${CSS}</style>
</head>
<body>
  <input type="checkbox" id="newest-toggle" class="toggle-input" aria-hidden="true">
  <input type="checkbox" id="thinking-toggle" class="toggle-input" aria-hidden="true">
  <input type="checkbox" id="tools-toggle" class="toggle-input" aria-hidden="true">
  <header class="app-header">
    <div class="header-inner">
      <div class="session-id-block">
        <p class="eyebrow">what7 share · agentsview-style transcript</p>
        <h1>${escapeHtml(title)}</h1>
        <div class="session-meta">
          <span>${escapeHtml(agent)}</span>
          <span>${escapeHtml(model)}</span>
          <span>${escapeHtml(project)}</span>
          ${duration ? `<span>${escapeHtml(duration)}</span>` : ""}
        </div>
      </div>
      <div class="controls" aria-label="Viewer controls">
        <input id="search" class="search" type="search" placeholder="Search transcript…" autocomplete="off">
        <label for="thinking-toggle" class="toggle-label" title="Show reasoning, metadata, and event blocks">Context</label>
        <label for="tools-toggle" class="toggle-label" title="Show or hide tool calls and outputs">Tools</label>
        <label for="newest-toggle" class="toggle-label" title="Reverse timeline order">Newest first</label>
        <button id="theme-btn" class="theme-btn" type="button">Dark</button>
        <button id="shortcuts-btn" class="theme-btn" type="button" aria-label="Keyboard shortcuts">?</button>
      </div>
    </div>
    <div class="summary-strip">
      ${stat("Messages", stats.messageCount)}
      ${stat("Tools", stats.toolCallCount + stats.toolResultCount, "tool-stat")}
      ${stat("Reasoning", stats.reasoningCount, "debug-stat")}
      ${stat("Lines", stats.lineCount, "debug-stat")}
      ${stat("Redactions", stats.redactionCount ?? 0, "debug-stat")}
    </div>
  </header>

  <aside class="source-card context-block" aria-label="Share metadata">
    <div><strong>Source</strong><code>${escapeHtml(sourcePath)}</code></div>
    <div><strong>Session</strong><code>${escapeHtml(transcript.sessionId ?? "unknown")}</code></div>
    <div><strong>Generated</strong><code>${escapeHtml(generatedAt)}</code></div>
    <p>Public share pages are static and unauthenticated. what7 redacts common secrets before render by default, but review sensitive sessions before publishing.</p>
  </aside>

  <main id="timeline" class="timeline" aria-label="Conversation timeline">
    ${body || `<p class="empty">No transcript items found.</p>`}
  </main>

  <dialog id="shortcuts" class="shortcuts">
    <h2>Keyboard shortcuts</h2>
    <dl>
      <div><dt>/</dt><dd>Focus search</dd></div>
      <div><dt>t</dt><dd>Toggle tool blocks</dd></div>
      <div><dt>c</dt><dd>Toggle context / reasoning</dd></div>
      <div><dt>n</dt><dd>Newest first</dd></div>
      <div><dt>d</dt><dd>Dark / light</dd></div>
      <div><dt>Esc</dt><dd>Clear search or close this dialog</dd></div>
    </dl>
    <button type="button" id="close-shortcuts">Close</button>
  </dialog>

  <footer class="page-footer">
    <span>Share artifact generated by what7.</span>
    <span>Inspired by <a href="https://github.com/wesm/agentsview" rel="noreferrer noopener" target="_blank">agentsview</a>.</span>
  </footer>
  <script>${JS}</script>
</body>
</html>`;

  return { html, title, redactionCount: redaction.count, stats };
}

function buildDisplayItems(items: TimelineItem[]): DisplayItem[] {
  const out: DisplayItem[] = [];
  for (let index = 0; index < items.length; index += 1) {
    const item = items[index];
    if (!item) continue;
    const next = items[index + 1];
    if (item.kind === "tool_call" && next?.kind === "tool_result" && (!item.callId || item.callId === next.callId)) {
      out.push({ kind: "tool-pair", call: item, result: next });
      index += 1;
      continue;
    }
    out.push({ kind: "timeline", item });
  }
  return out;
}

function renderDisplayItem(display: DisplayItem, maxInlineChars: number): string {
  if (display.kind === "tool-pair") return renderToolPair(display.call, display.result, maxInlineChars);
  return renderItem(display.item, maxInlineChars);
}

function renderItem(item: TimelineItem, maxInlineChars: number): string {
  if (item.kind === "tool_call") return renderToolPair(item, undefined, maxInlineChars);
  const classes = ["item", `kind-${item.kind}`, item.role ? `role-${item.role}` : "", isContextKind(item.kind) ? "context-block" : ""].filter(Boolean).join(" ");
  const title = item.kind === "message" ? roleLabel(item.role) : item.title;
  const meta = metaParts(item).join(" · ");
  const tooLong = item.content.length > maxInlineChars;
  const rendered = renderMarkdown(item.content);
  const preview = tooLong ? renderMarkdown(`${item.content.slice(0, maxInlineChars)}\n\n… preview truncated; expand for full content.`) : rendered;
  const dataText = escapeHtml(`${title} ${meta} ${item.content}`.slice(0, 50_000));

  if (item.kind === "tool_result") {
    return renderToolPair({ ...item, kind: "tool_call", title: "Tool output" }, item, maxInlineChars);
  }

  const content = item.collapsed || tooLong || isContextKind(item.kind)
    ? `<details ${item.collapsed === false && !tooLong ? "open" : ""}>
        <summary><span>${escapeHtml(title)}</span><em>${escapeHtml(meta)}</em></summary>
        ${tooLong ? `<div class="preview">${preview}</div><div class="full"><h4>Full content</h4>${rendered}</div>` : rendered}
      </details>`
    : `<div class="item-head"><strong>${escapeHtml(title)}</strong><span>${escapeHtml(meta)}</span></div><div class="content">${rendered}</div>`;

  return `<article id="${escapeHtml(item.id)}" class="${classes}" data-kind="${escapeHtml(item.kind)}" data-role="${escapeHtml(item.role ?? "")}" data-text="${dataText}">${content}</article>`;
}

function renderToolPair(call: TimelineItem, result: TimelineItem | undefined, maxInlineChars: number): string {
  const title = call.toolName ?? (call.title.replace(/^Tool call:\s*/i, "") || "tool");
  const combined = `${call.content}\n${result?.content ?? ""}`;
  const meta = metaParts(call).join(" · ");
  const inputTooLong = call.content.length > maxInlineChars;
  const outputTooLong = Boolean(result && result.content.length > maxInlineChars);
  const inputPreview = inputTooLong ? `${call.content.slice(0, maxInlineChars)}\n\n… input preview truncated.` : call.content;
  const outputPreview = result && outputTooLong ? `${result.content.slice(0, maxInlineChars)}\n\n… output preview truncated.` : result?.content;
  const preview = firstLine(call.content) || firstLine(result?.content ?? "") || "tool call";

  return `<article id="${escapeHtml(call.id)}" class="item kind-tool tool-card" data-kind="tool" data-text="${escapeHtml(`${title} ${meta} ${combined}`.slice(0, 50_000))}">
    <details>
      <summary>
        <span class="tool-title"><b>${escapeHtml(displayToolName(title))}</b><code>${escapeHtml(preview)}</code></span>
        <em>${escapeHtml(meta)}</em>
      </summary>
      <section class="tool-section">
        <h3>Input</h3>
        ${renderMarkdown(inputPreview)}
        ${inputTooLong ? `<details class="nested"><summary>Full input</summary>${renderMarkdown(call.content)}</details>` : ""}
      </section>
      ${result ? `<section class="tool-section output"><h3>Output</h3>${renderMarkdown(outputPreview ?? "")}${outputTooLong ? `<details class="nested"><summary>Full output</summary>${renderMarkdown(result.content)}</details>` : ""}</section>` : ""}
    </details>
  </article>`;
}

function metaParts(item: TimelineItem): string[] {
  return [
    item.timestamp,
    `line ${item.line}`,
    item.rawType,
    item.callId ? `call ${item.callId}` : undefined,
  ].filter((value): value is string => Boolean(value));
}

function renderMarkdown(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const chunks: string[] = [];
  let paragraph: string[] = [];
  let list: string[] = [];
  let code: string[] | null = null;
  let codeLang = "";

  const flushParagraph = () => {
    if (paragraph.length) {
      chunks.push(`<p>${paragraph.map(inline).join("<br>")}</p>`);
      paragraph = [];
    }
  };
  const flushList = () => {
    if (list.length) {
      chunks.push(`<ul>${list.map((item) => `<li>${inline(item)}</li>`).join("")}</ul>`);
      list = [];
    }
  };

  for (const line of lines) {
    const fence = line.match(/^```\s*([A-Za-z0-9_-]+)?\s*$/);
    if (fence) {
      if (code) {
        chunks.push(`<pre class="code"><code${codeLang ? ` data-lang="${escapeHtml(codeLang)}"` : ""}>${escapeHtml(code.join("\n"))}</code></pre>`);
        code = null;
        codeLang = "";
      } else {
        flushParagraph();
        flushList();
        code = [];
        codeLang = fence[1] ?? "";
      }
      continue;
    }

    if (code) {
      code.push(line);
      continue;
    }

    if (!line.trim()) {
      flushParagraph();
      flushList();
      continue;
    }

    const heading = line.match(/^(#{1,3})\s+(.+)$/);
    if (heading) {
      flushParagraph();
      flushList();
      const level = heading[1]?.length ?? 2;
      chunks.push(`<h${level + 1}>${inline(heading[2] ?? "")}</h${level + 1}>`);
      continue;
    }

    const bullet = line.match(/^\s*[-*]\s+(.+)$/);
    if (bullet) {
      flushParagraph();
      list.push(bullet[1] ?? "");
      continue;
    }

    const quote = line.match(/^>\s?(.+)$/);
    if (quote) {
      flushParagraph();
      flushList();
      chunks.push(`<blockquote>${inline(quote[1] ?? "")}</blockquote>`);
      continue;
    }

    paragraph.push(line);
  }

  if (code) chunks.push(`<pre class="code"><code>${escapeHtml(code.join("\n"))}</code></pre>`);
  flushParagraph();
  flushList();
  return chunks.join("\n");
}

function inline(text: string): string {
  const parts = text.split(/(`[^`]+`)/g);
  return parts
    .map((part) => {
      if (part.startsWith("`") && part.endsWith("`") && part.length >= 2) {
        return `<code>${escapeHtml(part.slice(1, -1))}</code>`;
      }
      return linkify(escapeHtml(part));
    })
    .join("");
}

function linkify(escaped: string): string {
  return escaped.replace(/\bhttps?:\/\/[^\s<]+/g, (url) => {
    const safe = url.replace(/&quot;|&#39;|&lt;|&gt;/g, "");
    return `<a href="${safe}" rel="noreferrer noopener" target="_blank">${url}</a>`;
  });
}

function roleLabel(role: TimelineItem["role"]): string {
  if (role === "user") return "User";
  if (role === "assistant") return "Assistant";
  if (role === "system") return "System";
  if (role === "tool") return "Tool";
  return "Message";
}

function stat(label: string, value: number, className = ""): string {
  return `<div class="${["stat", className].filter(Boolean).join(" ")}"><dt>${escapeHtml(label)}</dt><dd>${value}</dd></div>`;
}

function displayToolName(name: string): string {
  if (name === "exec_command") return "Shell";
  if (name === "write_stdin") return "Stdin";
  if (name === "apply_patch") return "Patch";
  if (name === "read_file") return "Read";
  if (name === "write_file") return "Write";
  if (name === "edit_file") return "Edit";
  if (name === "grep") return "Grep";
  if (name === "glob") return "Glob";
  if (name === "shell_command") return "Shell";
  if (name === "read_directory") return "List Dir";
  if (name === "read_multiple_files") return "Read";
  if (name === "todo_write") return "Todo";
  if (name === "think") return "Think";
  if (name === "explore") return "Explore";
  return name;
}

function isContextKind(kind: TimelineItem["kind"]): boolean {
  return kind === "reasoning" || kind === "metadata" || kind === "event";
}

function firstLine(text: string): string {
  return text.trim().split(/\r?\n/)[0]?.slice(0, 120) ?? "";
}

function deriveProject(transcript: Transcript, sourcePath: string): string {
  const cwd = stringMeta(transcript.metadata.cwd);
  if (cwd) return path.basename(cwd) || cwd;
  return path.basename(path.dirname(sourcePath)) || "project";
}

function deriveAgent(transcript: Transcript, sourcePath: string): string {
  const agent = stringMeta(transcript.metadata.agent) ?? stringMeta(transcript.metadata.agent_type);
  if (agent) return agent;
  return sourcePath.includes(".codex") || transcript.items.some((item) => item.rawType?.includes("function_call")) ? "Codex" : "Agent";
}

function stringMeta(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

function formatDuration(start?: string, end?: string): string {
  if (!start || !end) return "";
  const startMs = Date.parse(start);
  const endMs = Date.parse(end);
  if (!Number.isFinite(startMs) || !Number.isFinite(endMs) || endMs <= startMs) return "";
  const seconds = Math.round((endMs - startMs) / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const rest = seconds % 60;
  if (minutes < 60) return `${minutes}m ${rest}s`;
  const hours = Math.floor(minutes / 60);
  return `${hours}h ${minutes % 60}m`;
}

export function escapeHtml(input: string): string {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

const CSS = `
:root {
  color-scheme: light;
  --share-bg: #faf7ee; --share-surface: #ffffff; --share-ink: #1a1a18;
  --share-fg2: #4a4842; --share-fg3: #807c70;
  --share-line: #e6decb; --share-line2: #d2c9b0;
  --brand-orange: #c9622d; --brand-orange-soft: #fdf0e0; --brand-orange-line: #f3d8b5;
  --user-bg: #fbf2dc; --tool-bg: #f6efd9; --context-bg: #f3edd8;
  --code-bg: #1f1d18; --code-text: #ece4cf;
  --radius-sm: 4px; --radius-md: 6px; --radius-lg: 10px;
  --font-sans-ui: Inter, "SF Pro Text", -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
  --font-serif-read: "Tiempos Text", "Source Serif 4", "Iowan Old Style", Charter, Georgia, serif;
  --font-mono: ui-monospace, "JetBrains Mono", "SF Mono", Menlo, Consolas, monospace;
  --font-sans: var(--font-sans-ui);
  --measure: 760px;
}
:root.dark { color-scheme: dark; --share-bg: #18181b; --share-surface: #212126; --share-ink: #ececef; --share-fg2: #a1a1aa; --share-fg3: #71717a; --share-line: #2c2c33; --share-line2: #3a3a44; --brand-orange: #e88c4e; --brand-orange-soft: #2a1d12; --brand-orange-line: #4a3220; --user-bg: #1e1d18; --tool-bg: #1c1c1f; --context-bg: #1a1a1d; --code-bg: #0f0f12; --code-text: #e4e4e7; }
* { box-sizing: border-box; }
body { margin: 0; font: 14.5px/1.55 var(--font-sans-ui); background: var(--share-bg); color: var(--share-ink); -webkit-font-smoothing: antialiased; text-wrap: pretty; }
a { color: var(--brand-orange); text-decoration: underline; text-decoration-thickness: 1px; text-underline-offset: 2px; }
a:hover { text-decoration-thickness: 2px; }
code, pre, kbd { font-family: var(--font-mono); }
.toggle-input { position: absolute; opacity: 0; pointer-events: none; }

/* Hero header (compact docs style) */
.app-header { background: transparent; box-shadow: none; backdrop-filter: none; padding: 32px 24px 14px; border-bottom: 1px solid var(--share-line); }
.header-inner { max-width: var(--measure); margin: 0 auto; display: block; }
.session-id-block { margin: 0; }
.eyebrow { margin: 0 0 6px; color: var(--brand-orange); font-size: 11px; font-weight: 600; letter-spacing: .08em; text-transform: uppercase; }
h1 { margin: 0; font-size: clamp(20px, 2.4vw, 26px); font-weight: 600; line-height: 1.25; letter-spacing: -0.01em; color: var(--share-ink); }
.session-meta { display: flex; flex-wrap: wrap; gap: 0; margin-top: 6px; color: var(--share-fg2); font-size: 12.5px; }
.session-meta span { padding: 0 10px 0 0; margin-right: 10px; box-shadow: 1px 0 0 var(--share-line2); }
.session-meta span:last-child { margin-right: 0; padding-right: 0; box-shadow: none; }

/* Toolbar: sticky compact strip */
.controls { position: sticky; top: 0; z-index: 50; max-width: var(--measure); margin: 0 auto; display: flex; flex-wrap: wrap; gap: 4px; align-items: center; padding: 8px 24px; background: color-mix(in srgb, var(--share-bg) 92%, transparent); backdrop-filter: blur(8px); border-bottom: 1px solid var(--share-line); }
.search { min-width: 120px; flex: 0 1 220px; min-height: 26px; padding: 4px 9px; border: 1px solid var(--share-line); border-radius: var(--radius-sm); background: var(--share-surface); color: var(--share-ink); font: 12.5px var(--font-sans-ui); }
.search:focus { outline: 0; border-color: var(--brand-orange); }
.toggle-label, .theme-btn { display: inline-flex; align-items: center; min-height: 24px; padding: 3px 8px; border: 0; border-radius: var(--radius-sm); background: transparent; color: var(--share-fg2); cursor: pointer; font: 12px var(--font-sans-ui); font-weight: 500; transition: background 120ms, color 120ms; }
.toggle-label:hover, .theme-btn:hover { background: var(--share-line); color: var(--share-ink); }
#thinking-toggle:checked ~ .app-header label[for="thinking-toggle"], #tools-toggle:checked ~ .app-header label[for="tools-toggle"], #newest-toggle:checked ~ .app-header label[for="newest-toggle"] { background: var(--brand-orange); color: #fff; }

/* Stats inline byline */
.summary-strip { max-width: var(--measure); margin: 0 auto; padding: 8px 24px 0; display: flex; flex-wrap: wrap; gap: 14px; font-size: 12px; color: var(--share-fg3); }
.stat { margin: 0; padding: 0; background: transparent; border: 0; display: inline; }
.stat dt { display: inline; color: var(--share-fg3); font-size: 12px; }
.stat dd { display: inline; margin: 0 0 0 4px; font-size: 12px; font-weight: 600; font-variant-numeric: tabular-nums; color: var(--share-fg2); }
.tool-stat, .debug-stat { display: none; }
#tools-toggle:checked ~ .app-header .tool-stat, #thinking-toggle:checked ~ .app-header .debug-stat { display: inline; }

/* Source metadata: thin compact strip */
.source-card { max-width: var(--measure); margin: 12px auto 0; padding: 10px 24px; display: grid; gap: 4px; color: var(--share-fg2); font-size: 12px; border-top: 1px solid var(--share-line); border-bottom: 1px solid var(--share-line); background: color-mix(in srgb, var(--share-surface) 50%, transparent); }
.source-card div { display: grid; grid-template-columns: 72px minmax(0, 1fr); gap: 10px; align-items: baseline; }
.source-card strong { color: var(--share-fg3); font-weight: 600; text-transform: uppercase; letter-spacing: .06em; font-size: 10.5px; }
.source-card code { overflow-wrap: anywhere; color: var(--share-fg2); font-size: 11.5px; background: transparent; border: 0; padding: 0; }
.source-card p { margin: 4px 0 0; font-size: 12px; color: var(--share-fg3); }

/* Timeline */
.timeline { max-width: var(--measure); margin: 0 auto; padding: 16px 24px 32px; display: flex; flex-direction: column; gap: 10px; }
#newest-toggle:checked ~ .timeline { flex-direction: column-reverse; }
.item { padding: 0; background: transparent; border: 0; box-shadow: none; border-radius: 0; }
.item.hidden { display: none !important; }

/* Roles */
.role-user { padding: 7px 12px 7px 12px; background: var(--user-bg); border-left: 2px solid var(--brand-orange); border-radius: 0 var(--radius-sm) var(--radius-sm) 0; font-size: 13.5px; line-height: 1.5; color: var(--share-ink); }
.role-assistant { font-size: 14.5px; line-height: 1.6; color: var(--share-ink); padding: 2px 0; }

/* Tools */
.kind-tool { font-size: 13px; }
.kind-tool > details { background: var(--share-surface); border: 1px solid var(--share-line); border-radius: var(--radius-sm); padding: 6px 12px; }
.kind-error > details { border-color: #d4756a; }

/* Reasoning / context */
.context-block { display: none; padding: 8px 12px; background: var(--share-bg); border: 1px dashed var(--share-line2); border-radius: var(--radius-sm); font-size: 12.5px; color: var(--share-fg2); }
#thinking-toggle:checked ~ .timeline .context-block { display: block; }
#tools-toggle:not(:checked) ~ .timeline .kind-tool { display: none; }

/* Item heads */
.item-head, details summary { display: flex; justify-content: space-between; gap: 12px; align-items: baseline; }
.item-head { margin-bottom: 3px; }
.item-head strong, details summary span { font-weight: 600; font-size: 10.5px; letter-spacing: .06em; text-transform: uppercase; color: var(--share-fg3); }
.role-user .item-head strong { color: var(--brand-orange); }
.item-head span, details summary em { color: var(--share-fg3); font-size: 11px; font-style: normal; text-align: right; }
details summary { cursor: pointer; min-height: 22px; align-items: center; list-style: none; }
details summary::-webkit-details-marker { display: none; }
details summary::before { content: "▸"; display: inline-block; margin-right: 6px; color: var(--share-fg3); font-size: 9px; transition: transform 120ms ease; }
details[open] > summary::before { transform: rotate(90deg); }
.content, details > p, details > ul, details > pre, details > blockquote, details > h2, details > h3, details > h4, .preview, .full, .tool-section { margin-top: 6px; }

/* Prose */
p { margin: .5em 0; overflow-wrap: anywhere; }
ul { padding-left: 1.3rem; margin: .4em 0; }
ul li { margin: .15em 0; }
blockquote { margin: .7em 0; padding: 2px 0 2px 12px; border-left: 2px solid var(--brand-orange-line); color: var(--share-fg2); }
h2, h3, h4 { font-weight: 600; line-height: 1.3; color: var(--share-ink); letter-spacing: -0.005em; }
h2 { font-size: 17px; margin: 1.2em 0 .35em; }
h3 { font-size: 14.5px; margin: 1em 0 .3em; }
h4 { font-size: 13px; margin: .9em 0 .25em; }
pre.code { max-height: 28rem; overflow: auto; padding: 10px 14px; background: var(--code-bg); color: var(--code-text); border-radius: var(--radius-sm); border: 0; font-size: 12.5px; line-height: 1.5; }
code { background: var(--share-line); border: 0; border-radius: 3px; padding: 1px 5px; font-size: .9em; color: var(--share-ink); }
pre code { background: transparent; border: none; padding: 0; color: inherit; font-size: 12.5px; }

/* Tool internals */
.tool-title { display: inline-flex; flex-wrap: wrap; gap: 8px; align-items: baseline; min-width: 0; }
.tool-title b { color: var(--brand-orange); font-weight: 600; font-size: 11px; letter-spacing: .06em; text-transform: uppercase; }
.tool-title code { max-width: 480px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; background: transparent; padding: 0; font-size: 12px; color: var(--share-fg2); }
.tool-section { margin-top: 8px; padding-top: 6px; border-top: 1px dashed var(--share-line); }
.tool-section h3 { margin: 0 0 4px; font-size: 10px; font-weight: 700; color: var(--share-fg3); text-transform: uppercase; letter-spacing: .06em; }
.nested { margin-top: 6px; border: 1px dashed var(--share-line2); border-radius: var(--radius-sm); padding: 6px 10px; }

/* Shortcuts dialog */
.shortcuts { border: 1px solid var(--share-line2); border-radius: var(--radius-md); background: var(--share-surface); color: var(--share-ink); max-width: 380px; padding: 18px 22px; }
.shortcuts::backdrop { background: rgba(20,15,5,.4); }
.shortcuts h2 { margin-top: 0; font-size: 16px; }
.shortcuts dl div { display: grid; grid-template-columns: 56px 1fr; gap: 12px; padding: 4px 0; font-size: 13px; }
.shortcuts dt { font-family: var(--font-mono); font-weight: 600; color: var(--brand-orange); font-size: 12px; }
.shortcuts button { margin-top: 10px; padding: 6px 12px; border: 1px solid var(--share-line2); border-radius: var(--radius-sm); background: transparent; cursor: pointer; font: 12.5px var(--font-sans-ui); color: var(--share-ink); transition: background 120ms; }
.shortcuts button:hover { background: var(--brand-orange); color: #fff; border-color: var(--brand-orange); }

.empty { color: var(--share-fg3); text-align: center; padding: 60px 20px; }

/* Footer */
.page-footer { max-width: var(--measure); margin: 24px auto 0; padding: 16px 24px 40px; display: flex; flex-direction: column; align-items: flex-start; gap: 4px; color: var(--share-fg3); font-size: 12px; border-top: 1px solid var(--share-line); }
.page-footer a { color: var(--brand-orange); }
.page-footer span:first-child { font-size: 13px; color: var(--share-fg2); }

@media (max-width: 720px) {
  .app-header { padding: 24px 16px 12px; }
  .controls { padding: 6px 16px; }
  .source-card { padding: 10px 16px; }
  .source-card div { grid-template-columns: 1fr; gap: 1px; }
  .timeline { padding: 14px 16px 28px; gap: 8px; }
  .item-head, details summary { display: block; }
  .item-head span, details summary em { display: block; text-align: left; margin-top: 2px; }
  .search { font-size: 16px; }
  .page-footer { padding: 12px 16px 32px; }
}
`;

const JS = `
(() => {
  const root = document.documentElement;
  const searchParams = new URLSearchParams(window.location.search);
  const toolsToggle = document.getElementById('tools-toggle');
  const contextToggle = document.getElementById('thinking-toggle');
  if (toolsToggle && (searchParams.get('tools') === '1' || searchParams.get('debug') === '1')) toolsToggle.checked = true;
  if (contextToggle && (searchParams.get('context') === '1' || searchParams.get('events') === '1' || searchParams.get('reasoning') === '1' || searchParams.get('debug') === '1')) contextToggle.checked = true;
  const stored = localStorage.getItem('what7-theme');
  if (stored === 'dark' || (!stored && matchMedia('(prefers-color-scheme: dark)').matches)) root.classList.add('dark');
  const themeBtn = document.getElementById('theme-btn');
  const syncTheme = () => { if (themeBtn) themeBtn.textContent = root.classList.contains('dark') ? 'Light' : 'Dark'; };
  themeBtn?.addEventListener('click', () => { root.classList.toggle('dark'); localStorage.setItem('what7-theme', root.classList.contains('dark') ? 'dark' : 'light'); syncTheme(); });
  syncTheme();

  const search = document.getElementById('search');
  const items = Array.from(document.querySelectorAll('.timeline .item'));
  function applySearch() {
    const q = String(search?.value || '').trim().toLowerCase();
    for (const item of items) {
      const hay = (item.getAttribute('data-text') || item.textContent || '').toLowerCase();
      item.classList.toggle('hidden', Boolean(q) && !hay.includes(q));
      if (q && hay.includes(q)) item.querySelector('details')?.setAttribute('open', '');
    }
  }
  search?.addEventListener('input', applySearch);

  const shortcuts = document.getElementById('shortcuts');
  document.getElementById('shortcuts-btn')?.addEventListener('click', () => shortcuts?.showModal());
  document.getElementById('close-shortcuts')?.addEventListener('click', () => shortcuts?.close());

  document.addEventListener('keydown', (event) => {
    const tag = document.activeElement?.tagName;
    const inInput = tag === 'INPUT' || tag === 'TEXTAREA';
    if (event.key === 'Escape') { if (shortcuts?.open) shortcuts.close(); else if (search) { search.value = ''; applySearch(); search.blur(); } return; }
    if (inInput) return;
    if (event.key === '/') { event.preventDefault(); search?.focus(); }
    if (event.key.toLowerCase() === 't') document.getElementById('tools-toggle')?.click();
    if (event.key.toLowerCase() === 'c') document.getElementById('thinking-toggle')?.click();
    if (event.key.toLowerCase() === 'n') document.getElementById('newest-toggle')?.click();
    if (event.key.toLowerCase() === 'd') themeBtn?.click();
    if (event.key === '?') shortcuts?.showModal();
  });
})();
`;
