import path from "node:path";
import type { RenderOptions, RenderResult, TimelineItem, Transcript } from "./types.js";
import { redactObjectStrings } from "./redaction.js";

const DEFAULT_MAX_INLINE_CHARS = 3_500;

type DisplayItem =
  | { kind: "timeline"; item: TimelineItem }
  | { kind: "tool-pair"; call: TimelineItem; result?: TimelineItem };

export function renderTranscript(input: Transcript, options: RenderOptions = {}): RenderResult {
  const redaction = options.redact === false ? { value: input, count: 0 } : redactObjectStrings(input);
  const transcript = redaction.value;
  const title = options.title ?? transcript.title ?? "Codex session";
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const maxInlineChars = options.maxInlineChars ?? DEFAULT_MAX_INLINE_CHARS;
  const displayItems = buildDisplayItems(transcript.items);
  const sourcePath = options.sourcePath ?? transcript.sourcePath;
  const project = deriveProject(transcript, sourcePath);
  const agent = deriveAgent(transcript, sourcePath);
  const model = stringMeta(transcript.metadata.model) ?? stringMeta(transcript.metadata.currentModel) ?? "unknown model";
  const duration = formatDuration(transcript.startedAt, transcript.endedAt);

  const body = displayItems.map((item) => renderDisplayItem(item, maxInlineChars)).join("\n");
  const stats = { ...transcript.stats, redactionCount: redaction.count };

  const html = `<!doctype html>
<html lang="zh-CN" data-theme="auto">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)} · what7</title>
  <style>${CSS}</style>
</head>
<body>
  <input type="checkbox" id="newest-toggle" class="toggle-input" aria-hidden="true">
  <input type="checkbox" id="thinking-toggle" class="toggle-input" aria-hidden="true">
  <input type="checkbox" id="tools-toggle" class="toggle-input" aria-hidden="true" checked>
  <header class="app-header">
    <div class="header-inner">
      <div class="session-id-block">
        <p class="eyebrow">what7 share · agentsview-style transcript</p>
        <h1>${escapeHtml(title)}</h1>
        <div class="session-meta">
          <span>${escapeHtml(agent)}</span>
          <span>${escapeHtml(model)}</span>
          <span>${escapeHtml(project)}</span>
          ${duration ? `<span>${escapeHtml(duration)}</span>` : ""}
        </div>
      </div>
      <div class="controls" aria-label="Viewer controls">
        <input id="search" class="search" type="search" placeholder="Search transcript…" autocomplete="off">
        <label for="thinking-toggle" class="toggle-label" title="Show reasoning, metadata, and event blocks">Context</label>
        <label for="tools-toggle" class="toggle-label" title="Show or hide tool calls and outputs">Tools</label>
        <label for="newest-toggle" class="toggle-label" title="Reverse timeline order">Newest first</label>
        <button id="theme-btn" class="theme-btn" type="button">Dark</button>
        <button id="shortcuts-btn" class="theme-btn" type="button">?</button>
      </div>
    </div>
    <div class="summary-strip">
      ${stat("Messages", stats.messageCount)}
      ${stat("Tools", stats.toolCallCount + stats.toolResultCount)}
      ${stat("Reasoning", stats.reasoningCount)}
      ${stat("Lines", stats.lineCount)}
      ${stat("Redactions", stats.redactionCount ?? 0)}
    </div>
  </header>

  <aside class="source-card" aria-label="Share metadata">
    <div><strong>Source</strong><code>${escapeHtml(sourcePath)}</code></div>
    <div><strong>Session</strong><code>${escapeHtml(transcript.sessionId ?? "unknown")}</code></div>
    <div><strong>Generated</strong><code>${escapeHtml(generatedAt)}</code></div>
    <p>Public share pages are static and unauthenticated. what7 redacts common secrets before render by default, but review sensitive sessions before publishing.</p>
  </aside>

  <main id="timeline" class="timeline" aria-label="Conversation timeline">
    ${body || `<p class="empty">No transcript items found.</p>`}
  </main>

  <dialog id="shortcuts" class="shortcuts">
    <h2>Keyboard shortcuts</h2>
    <dl>
      <div><dt>/</dt><dd>Focus search</dd></div>
      <div><dt>t</dt><dd>Toggle tool blocks</dd></div>
      <div><dt>c</dt><dd>Toggle context / reasoning</dd></div>
      <div><dt>n</dt><dd>Newest first</dd></div>
      <div><dt>d</dt><dd>Dark / light</dd></div>
      <div><dt>Esc</dt><dd>Clear search or close this dialog</dd></div>
    </dl>
    <button type="button" id="close-shortcuts">Close</button>
  </dialog>

  <footer class="page-footer">
    <span>Share artifact generated by what7.</span>
    <span>Inspired by <a href="https://github.com/wesm/agentsview" rel="noreferrer noopener" target="_blank">agentsview</a>.</span>
  </footer>
  <script>${JS}</script>
</body>
</html>`;

  return { html, title, redactionCount: redaction.count, stats };
}

function buildDisplayItems(items: TimelineItem[]): DisplayItem[] {
  const out: DisplayItem[] = [];
  for (let index = 0; index < items.length; index += 1) {
    const item = items[index];
    if (!item) continue;
    const next = items[index + 1];
    if (item.kind === "tool_call" && next?.kind === "tool_result" && (!item.callId || item.callId === next.callId)) {
      out.push({ kind: "tool-pair", call: item, result: next });
      index += 1;
      continue;
    }
    out.push({ kind: "timeline", item });
  }
  return out;
}

function renderDisplayItem(display: DisplayItem, maxInlineChars: number): string {
  if (display.kind === "tool-pair") return renderToolPair(display.call, display.result, maxInlineChars);
  return renderItem(display.item, maxInlineChars);
}

function renderItem(item: TimelineItem, maxInlineChars: number): string {
  if (item.kind === "tool_call") return renderToolPair(item, undefined, maxInlineChars);
  const classes = ["item", `kind-${item.kind}`, item.role ? `role-${item.role}` : "", isContextKind(item.kind) ? "context-block" : ""].filter(Boolean).join(" ");
  const title = item.kind === "message" ? roleLabel(item.role) : item.title;
  const meta = metaParts(item).join(" · ");
  const tooLong = item.content.length > maxInlineChars;
  const rendered = renderMarkdown(item.content);
  const preview = tooLong ? renderMarkdown(`${item.content.slice(0, maxInlineChars)}\n\n… preview truncated; expand for full content.`) : rendered;
  const dataText = escapeHtml(`${title} ${meta} ${item.content}`.slice(0, 50_000));

  if (item.kind === "tool_result") {
    return renderToolPair({ ...item, kind: "tool_call", title: "Tool output" }, item, maxInlineChars);
  }

  const content = item.collapsed || tooLong || isContextKind(item.kind)
    ? `<details ${item.collapsed === false && !tooLong ? "open" : ""}>
        <summary><span>${escapeHtml(title)}</span><em>${escapeHtml(meta)}</em></summary>
        ${tooLong ? `<div class="preview">${preview}</div><div class="full"><h4>Full content</h4>${rendered}</div>` : rendered}
      </details>`
    : `<div class="item-head"><strong>${escapeHtml(title)}</strong><span>${escapeHtml(meta)}</span></div><div class="content">${rendered}</div>`;

  return `<article id="${escapeHtml(item.id)}" class="${classes}" data-kind="${escapeHtml(item.kind)}" data-role="${escapeHtml(item.role ?? "")}" data-text="${dataText}">${content}</article>`;
}

function renderToolPair(call: TimelineItem, result: TimelineItem | undefined, maxInlineChars: number): string {
  const title = call.toolName ?? (call.title.replace(/^Tool call:\s*/i, "") || "tool");
  const combined = `${call.content}\n${result?.content ?? ""}`;
  const meta = metaParts(call).join(" · ");
  const inputTooLong = call.content.length > maxInlineChars;
  const outputTooLong = Boolean(result && result.content.length > maxInlineChars);
  const inputPreview = inputTooLong ? `${call.content.slice(0, maxInlineChars)}\n\n… input preview truncated.` : call.content;
  const outputPreview = result && outputTooLong ? `${result.content.slice(0, maxInlineChars)}\n\n… output preview truncated.` : result?.content;
  const preview = firstLine(call.content) || firstLine(result?.content ?? "") || "tool call";

  return `<article id="${escapeHtml(call.id)}" class="item kind-tool tool-card" data-kind="tool" data-text="${escapeHtml(`${title} ${meta} ${combined}`.slice(0, 50_000))}">
    <details>
      <summary>
        <span class="tool-title"><b>${escapeHtml(displayToolName(title))}</b><code>${escapeHtml(preview)}</code></span>
        <em>${escapeHtml(meta)}</em>
      </summary>
      <section class="tool-section">
        <h3>Input</h3>
        ${renderMarkdown(inputPreview)}
        ${inputTooLong ? `<details class="nested"><summary>Full input</summary>${renderMarkdown(call.content)}</details>` : ""}
      </section>
      ${result ? `<section class="tool-section output"><h3>Output</h3>${renderMarkdown(outputPreview ?? "")}${outputTooLong ? `<details class="nested"><summary>Full output</summary>${renderMarkdown(result.content)}</details>` : ""}</section>` : ""}
    </details>
  </article>`;
}

function metaParts(item: TimelineItem): string[] {
  return [
    item.timestamp,
    `line ${item.line}`,
    item.rawType,
    item.callId ? `call ${item.callId}` : undefined,
  ].filter((value): value is string => Boolean(value));
}

function renderMarkdown(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const chunks: string[] = [];
  let paragraph: string[] = [];
  let list: string[] = [];
  let code: string[] | null = null;
  let codeLang = "";

  const flushParagraph = () => {
    if (paragraph.length) {
      chunks.push(`<p>${paragraph.map(inline).join("<br>")}</p>`);
      paragraph = [];
    }
  };
  const flushList = () => {
    if (list.length) {
      chunks.push(`<ul>${list.map((item) => `<li>${inline(item)}</li>`).join("")}</ul>`);
      list = [];
    }
  };

  for (const line of lines) {
    const fence = line.match(/^```\s*([A-Za-z0-9_-]+)?\s*$/);
    if (fence) {
      if (code) {
        chunks.push(`<pre class="code"><code${codeLang ? ` data-lang="${escapeHtml(codeLang)}"` : ""}>${escapeHtml(code.join("\n"))}</code></pre>`);
        code = null;
        codeLang = "";
      } else {
        flushParagraph();
        flushList();
        code = [];
        codeLang = fence[1] ?? "";
      }
      continue;
    }

    if (code) {
      code.push(line);
      continue;
    }

    if (!line.trim()) {
      flushParagraph();
      flushList();
      continue;
    }

    const heading = line.match(/^(#{1,3})\s+(.+)$/);
    if (heading) {
      flushParagraph();
      flushList();
      const level = heading[1]?.length ?? 2;
      chunks.push(`<h${level + 1}>${inline(heading[2] ?? "")}</h${level + 1}>`);
      continue;
    }

    const bullet = line.match(/^\s*[-*]\s+(.+)$/);
    if (bullet) {
      flushParagraph();
      list.push(bullet[1] ?? "");
      continue;
    }

    const quote = line.match(/^>\s?(.+)$/);
    if (quote) {
      flushParagraph();
      flushList();
      chunks.push(`<blockquote>${inline(quote[1] ?? "")}</blockquote>`);
      continue;
    }

    paragraph.push(line);
  }

  if (code) chunks.push(`<pre class="code"><code>${escapeHtml(code.join("\n"))}</code></pre>`);
  flushParagraph();
  flushList();
  return chunks.join("\n");
}

function inline(text: string): string {
  const parts = text.split(/(`[^`]+`)/g);
  return parts
    .map((part) => {
      if (part.startsWith("`") && part.endsWith("`") && part.length >= 2) {
        return `<code>${escapeHtml(part.slice(1, -1))}</code>`;
      }
      return linkify(escapeHtml(part));
    })
    .join("");
}

function linkify(escaped: string): string {
  return escaped.replace(/\bhttps?:\/\/[^\s<]+/g, (url) => {
    const safe = url.replace(/&quot;|&#39;|&lt;|&gt;/g, "");
    return `<a href="${safe}" rel="noreferrer noopener" target="_blank">${url}</a>`;
  });
}

function roleLabel(role: TimelineItem["role"]): string {
  if (role === "user") return "User";
  if (role === "assistant") return "Assistant";
  if (role === "system") return "System";
  if (role === "tool") return "Tool";
  return "Message";
}

function stat(label: string, value: number): string {
  return `<div class="stat"><dt>${escapeHtml(label)}</dt><dd>${value}</dd></div>`;
}

function displayToolName(name: string): string {
  if (name === "exec_command") return "Shell";
  if (name === "write_stdin") return "Stdin";
  if (name === "apply_patch") return "Patch";
  return name;
}

function isContextKind(kind: TimelineItem["kind"]): boolean {
  return kind === "reasoning" || kind === "metadata" || kind === "event";
}

function firstLine(text: string): string {
  return text.trim().split(/\r?\n/)[0]?.slice(0, 120) ?? "";
}

function deriveProject(transcript: Transcript, sourcePath: string): string {
  const cwd = stringMeta(transcript.metadata.cwd);
  if (cwd) return path.basename(cwd) || cwd;
  return path.basename(path.dirname(sourcePath)) || "project";
}

function deriveAgent(transcript: Transcript, sourcePath: string): string {
  const agent = stringMeta(transcript.metadata.agent) ?? stringMeta(transcript.metadata.agent_type);
  if (agent) return agent;
  return sourcePath.includes(".codex") || transcript.items.some((item) => item.rawType?.includes("function_call")) ? "Codex" : "Agent";
}

function stringMeta(value: unknown): string | undefined {
  return typeof value === "string" && value.trim() ? value : undefined;
}

function formatDuration(start?: string, end?: string): string {
  if (!start || !end) return "";
  const startMs = Date.parse(start);
  const endMs = Date.parse(end);
  if (!Number.isFinite(startMs) || !Number.isFinite(endMs) || endMs <= startMs) return "";
  const seconds = Math.round((endMs - startMs) / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  const rest = seconds % 60;
  if (minutes < 60) return `${minutes}m ${rest}s`;
  const hours = Math.floor(minutes / 60);
  return `${hours}h ${minutes % 60}m`;
}

export function escapeHtml(input: string): string {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

const CSS = `
:root {
  color-scheme: light;
  --bg-primary: #f7f7fa; --bg-surface: #ffffff; --bg-inset: #edeef3;
  --border-default: #dfe1e8; --border-muted: #e8eaf0;
  --text-primary: #1a1d26; --text-secondary: #5a6070; --text-muted: #8b92a0;
  --accent-blue: #2563eb; --accent-purple: #7c3aed; --accent-amber: #d97706; --accent-red: #dc2626; --accent-green: #059669;
  --user-bg: #eef2ff; --assistant-bg: #faf9ff; --context-bg: #f5f3ff; --tool-bg: #fffbf0;
  --code-bg: #1e1e2e; --code-text: #cdd6f4; --radius-sm: 4px; --radius-md: 8px;
  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif;
  --font-mono: "JetBrains Mono", "SF Mono", "Fira Code", Menlo, Consolas, monospace;
}
:root.dark { color-scheme: dark; --bg-primary: #0c0c10; --bg-surface: #15151b; --bg-inset: #101015; --border-default: #2a2a35; --border-muted: #222230; --text-primary: #e2e4e9; --text-secondary: #9ca3af; --text-muted: #6b7280; --accent-blue: #60a5fa; --accent-purple: #a78bfa; --accent-amber: #fbbf24; --accent-red: #f87171; --accent-green: #34d399; --user-bg: #111827; --assistant-bg: #141220; --context-bg: #1a1530; --tool-bg: #1a1508; --code-bg: #0d0d14; --code-text: #cdd6f4; }
* { box-sizing: border-box; }
body { margin: 0; font: 14px/1.55 var(--font-sans); background: var(--bg-primary); color: var(--text-primary); -webkit-font-smoothing: antialiased; }
a { color: var(--accent-blue); }
code, pre { font-family: var(--font-mono); }
.toggle-input { position: absolute; opacity: 0; pointer-events: none; }
.app-header { position: sticky; top: 0; z-index: 20; background: color-mix(in srgb, var(--bg-surface) 94%, transparent); backdrop-filter: blur(16px); border-bottom: 1px solid var(--border-default); }
.header-inner { max-width: 1120px; margin: 0 auto; padding: 12px 20px; display: grid; grid-template-columns: minmax(0, 1fr) minmax(320px, auto); gap: 16px; align-items: center; }
.eyebrow { margin: 0 0 3px; color: var(--accent-purple); font-size: 11px; font-weight: 750; letter-spacing: .08em; text-transform: uppercase; }
h1 { margin: 0; font-size: clamp(18px, 3vw, 28px); line-height: 1.12; }
.session-meta { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 6px; color: var(--text-muted); font-size: 12px; }
.session-meta span { border: 1px solid var(--border-muted); background: var(--bg-inset); padding: 2px 7px; border-radius: 999px; }
.controls { display: flex; flex-wrap: wrap; justify-content: flex-end; gap: 8px; }
.search { min-width: 220px; flex: 1 1 220px; padding: 7px 10px; border: 1px solid var(--border-default); border-radius: var(--radius-md); background: var(--bg-inset); color: var(--text-primary); }
.toggle-label, .theme-btn { display: inline-flex; align-items: center; gap: 4px; padding: 7px 10px; border: 1px solid var(--border-default); border-radius: var(--radius-md); background: var(--bg-inset); color: var(--text-primary); cursor: pointer; font: inherit; font-size: 12px; }
.toggle-label:hover, .theme-btn:hover { border-color: var(--accent-blue); }
#thinking-toggle:checked ~ .app-header label[for="thinking-toggle"], #tools-toggle:checked ~ .app-header label[for="tools-toggle"], #newest-toggle:checked ~ .app-header label[for="newest-toggle"] { background: var(--accent-blue); color: #fff; border-color: var(--accent-blue); }
.summary-strip { max-width: 1120px; margin: 0 auto; padding: 0 20px 12px; display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 8px; }
.stat { margin: 0; background: var(--bg-inset); border: 1px solid var(--border-muted); border-radius: var(--radius-md); padding: 8px 10px; }
.stat dt { color: var(--text-muted); font-size: 11px; }
.stat dd { margin: 1px 0 0; font-size: 18px; font-weight: 760; }
.source-card { max-width: 1120px; margin: 16px auto 0; padding: 12px 20px; display: grid; gap: 8px; color: var(--text-secondary); }
.source-card div { display: grid; grid-template-columns: 90px minmax(0, 1fr); gap: 10px; align-items: baseline; }
.source-card code { overflow-wrap: anywhere; color: var(--text-muted); }
.source-card p { margin: 4px 0 0; font-size: 12px; color: var(--text-muted); }
.timeline { max-width: 900px; margin: 0 auto; padding: 14px 16px 60px; display: flex; flex-direction: column; gap: 9px; }
#newest-toggle:checked ~ .timeline { flex-direction: column-reverse; }
.item { border-left: 4px solid var(--border-default); border-radius: 0 var(--radius-md) var(--radius-md) 0; padding: 14px 18px; background: var(--bg-surface); box-shadow: 0 10px 28px rgba(0,0,0,.04); }
.item.hidden { display: none !important; }
.role-user { background: var(--user-bg); border-left-color: var(--accent-blue); }
.role-assistant { background: var(--assistant-bg); border-left-color: var(--accent-purple); }
.kind-tool { background: var(--tool-bg); border-left-color: var(--accent-amber); }
.kind-error { border-left-color: var(--accent-red); }
.context-block { display: none; background: var(--context-bg); border-left-color: var(--accent-purple); }
#thinking-toggle:checked ~ .timeline .context-block { display: block; }
#tools-toggle:not(:checked) ~ .timeline .kind-tool { display: none; }
.item-head, details summary { display: flex; justify-content: space-between; gap: 14px; align-items: baseline; }
.item-head strong, details summary span { font-weight: 700; }
.item-head span, details summary em { color: var(--text-muted); font-size: 12px; font-style: normal; text-align: right; }
details summary { cursor: pointer; }
.content, details > p, details > ul, details > pre, details > blockquote, details > h2, details > h3, details > h4, .preview, .full, .tool-section { margin-top: 10px; }
p { margin: .7em 0; overflow-wrap: anywhere; white-space: pre-wrap; }
ul { padding-left: 1.2rem; }
blockquote { margin: .75rem 0; padding-left: 1rem; border-left: 3px solid var(--border-default); color: var(--text-secondary); }
pre.code { max-height: 30rem; overflow: auto; padding: 13px 16px; background: var(--code-bg); color: var(--code-text); border-radius: var(--radius-md); border: 1px solid var(--border-muted); }
code { background: color-mix(in srgb, var(--bg-inset) 86%, transparent); border: 1px solid var(--border-muted); border-radius: var(--radius-sm); padding: .1em .35em; font-size: .9em; }
pre code { background: transparent; border: none; padding: 0; color: inherit; }
.tool-title { display: inline-flex; flex-wrap: wrap; gap: 8px; align-items: baseline; min-width: 0; }
.tool-title b { color: var(--accent-amber); }
.tool-title code { max-width: 520px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.tool-section { border-top: 1px solid var(--border-muted); padding-top: 10px; }
.tool-section h3 { margin: 0 0 4px; font-size: 12px; color: var(--text-muted); text-transform: uppercase; letter-spacing: .06em; }
.nested { margin-top: 8px; border: 1px dashed var(--border-default); border-radius: var(--radius-md); padding: 8px 10px; }
.shortcuts { border: 1px solid var(--border-default); border-radius: 14px; background: var(--bg-surface); color: var(--text-primary); max-width: 420px; }
.shortcuts::backdrop { background: rgba(0,0,0,.35); }
.shortcuts h2 { margin-top: 0; }
.shortcuts dl div { display: grid; grid-template-columns: 48px 1fr; gap: 12px; padding: 5px 0; }
.shortcuts dt { font-family: var(--font-mono); font-weight: 700; }
.empty { color: var(--text-muted); text-align: center; }
.page-footer { display: flex; justify-content: center; flex-wrap: wrap; gap: 12px; border-top: 1px solid var(--border-default); padding: 18px; color: var(--text-muted); font-size: 12px; }
@media (max-width: 840px) { .header-inner { grid-template-columns: 1fr; } .controls { justify-content: flex-start; } .summary-strip { grid-template-columns: repeat(2, minmax(0, 1fr)); } .source-card div { grid-template-columns: 1fr; } .item-head, details summary { display: block; } .item-head span, details summary em { display: block; text-align: left; margin-top: 3px; } }
`;

const JS = `
(() => {
  const root = document.documentElement;
  const stored = localStorage.getItem('what7-theme');
  if (stored === 'dark' || (!stored && matchMedia('(prefers-color-scheme: dark)').matches)) root.classList.add('dark');
  const themeBtn = document.getElementById('theme-btn');
  const syncTheme = () => { if (themeBtn) themeBtn.textContent = root.classList.contains('dark') ? 'Light' : 'Dark'; };
  themeBtn?.addEventListener('click', () => { root.classList.toggle('dark'); localStorage.setItem('what7-theme', root.classList.contains('dark') ? 'dark' : 'light'); syncTheme(); });
  syncTheme();

  const search = document.getElementById('search');
  const items = Array.from(document.querySelectorAll('.timeline .item'));
  function applySearch() {
    const q = String(search?.value || '').trim().toLowerCase();
    for (const item of items) {
      const hay = (item.getAttribute('data-text') || item.textContent || '').toLowerCase();
      item.classList.toggle('hidden', Boolean(q) && !hay.includes(q));
      if (q && hay.includes(q)) item.querySelector('details')?.setAttribute('open', '');
    }
  }
  search?.addEventListener('input', applySearch);

  const shortcuts = document.getElementById('shortcuts');
  document.getElementById('shortcuts-btn')?.addEventListener('click', () => shortcuts?.showModal());
  document.getElementById('close-shortcuts')?.addEventListener('click', () => shortcuts?.close());

  document.addEventListener('keydown', (event) => {
    const tag = document.activeElement?.tagName;
    const inInput = tag === 'INPUT' || tag === 'TEXTAREA';
    if (event.key === 'Escape') { if (shortcuts?.open) shortcuts.close(); else if (search) { search.value = ''; applySearch(); search.blur(); } return; }
    if (inInput) return;
    if (event.key === '/') { event.preventDefault(); search?.focus(); }
    if (event.key.toLowerCase() === 't') document.getElementById('tools-toggle')?.click();
    if (event.key.toLowerCase() === 'c') document.getElementById('thinking-toggle')?.click();
    if (event.key.toLowerCase() === 'n') document.getElementById('newest-toggle')?.click();
    if (event.key.toLowerCase() === 'd') themeBtn?.click();
    if (event.key === '?') shortcuts?.showModal();
  });
})();
`;
